[workspace]
resolver = "2"

members = ["cli", "core"]

[workspace.package]
version = "0.8.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate's programmatic testing framework."
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/paritytech/try-runtime-cli"
repository = "https://github.com/paritytech/try-runtime-cli/"

[workspace.dependencies]
assert_cmd = { version = "2.0.16" }
async-trait = { version = "0.1.88" }
bytesize = { version = "2.0.1" }
clap = { version = "4.5.34" }
env_logger = { version = "0.11.7" }
hex = { version = "0.4.3", default-features = false }
itertools = { version = "0.14.0" }
log = { version = "0.4.27" }
parity-scale-codec = { version = "3.7.4" }
regex = { version = "1.11.1" }
serde = { version = "1.0.219" }
serde_json = { version = "1.0.140" }
strum = "0.27.1"
strum_macros = "0.27.1"
tempfile = { version = "3.19.1" }
tokio = { version = "1.44.1" }
zstd = { version = "0.13.2", default-features = false }

# Polkadot SDK
frame-remote-externalities = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }
frame-try-runtime = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }
frame-support = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }
frame-system = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }

sc-cli = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }
sc-executor = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }
sc-service = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }

sp-api = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }
sp-consensus-aura = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }
sp-consensus-babe = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }
sp-externalities = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }
sp-inherents = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }
sp-io = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }
sp-keystore = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }
sp-rpc = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }
sp-state-machine = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }
sp-storage = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }
sp-std = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }
sp-timestamp = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }
sp-transaction-storage-proof = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }
sp-version = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }
sp-weights = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }

substrate-cli-test-utils = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }
substrate-rpc-client = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }

polkadot-primitives = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }
cumulus-primitives-parachain-inherent = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }
cumulus-primitives-core = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }
cumulus-client-parachain-inherent = { git = "https://github.com/paritytech/polkadot-sdk", rev = "73157903c53f0b022c7f04f2968e60f19b2317df" }

# Local
try-runtime-core = { path = "core" }
