name: Update rust docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubicloud-standard-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.6.1"

      - uses: actions/checkout@v4
      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
          components: rust-src
        
      - name: Check if the README is up to date.
        run: |
          cargo install cargo-rdme --locked -q
          cargo rdme --check --workspace-project try-runtime-cli --readme-path README.md

      - name: Build docs
        uses: actions-rs/cargo@v1
        with:
          command: doc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
